#!/bin/bash
#系统信息统计页面

echo "<HTML>
    <HEAD>
              <TITLE>System Information Report</TITLE>
                  </HEAD>
              <BODY>
                  <H1>System Information Report</H1>
              </BODY>
    </HTML>"
